main = "tutorial_01_image"

[[graphs]]
name = "subgraph"
inputs = [{ name = "inp", cap = 16, ports = ["classify:inp"] }]
outputs = [{ name = "out", cap = 16, ports = ["classify:out"] }]
connections = [
]

    [[graphs.nodes]]
    name = "classify"
    ty = "Classify"
    path = "models/simple_classification_models/resnet18.mge"
    device = "cpu"
    device_id = 0
    
[[graphs]]
name = "tutorial_01_image"
connections = [
  { cap = 16, ports = ["source:out", "destination:inp"] },
  { cap = 16, ports = ["source:inp", "destination:out"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "ImageInput"
    urls = ["/path/to/your/images/"]
    
    [[graphs.nodes]]
    name = "destination"
    ty = "subgraph"
