main = "logical_test"

[[resources]]
name = "global_buf"
ty = "Buffer"
n = 10

[[nodes]]
name = "shared"
ty = "RepeatProcess"

[[graphs]]
name = "TransGraph0"
inputs = [{ name = "whatever", cap = 16, ports = ["shared:inp"] }]
connections = [
    { cap = 16, ports = ["shared:out", "trans:inp"] },
    { cap = 16, ports = ["trans:out", "destination:inp"] }
]

    [[graphs.nodes]]
    name = "trans"
    ty = "Transform"   

    [[graphs.nodes]]
    name = "destination"
    ty = "Printer"
    res = ["global_buf", "parent_buf", "buf"]

    [[graphs.resources]]
    name = "buf"
    ty = "Buffer"
    n = 5

[[graphs]]
name = "TransGraph1"
inputs = [{ name = "whatever", cap = 16, ports = ["shared:inp"] }]
connections = [
    { cap = 16, ports = ["shared:out", "trans:inp"] },
    { cap = 16, ports = ["trans:out", "destination:inp"] }
]

    [[graphs.nodes]]
    name = "trans"
    ty = "Transform"   

    [[graphs.nodes]]
    name = "destination"
    ty = "Printer"
    res = ["global_buf", "parent_buf", "buf"]

    [[graphs.resources]]
    name = "buf"
    ty = "Buffer"
    n = 10

[[graphs]]
name = "logical_test"
connections = [
  { cap = 1, ports = ["source:out", "demux:inp"] },
  { cap = 1, ports = ["demux:out", "destination:whatever"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "Source"
    n = 300
    
    [[graphs.nodes]]
    name = "demux"
    ty = "DynDemux"
    
    [[graphs.nodes]]
    name = "destination"
    ty = "TransGraph0|TransGraph1"
    res = ["parent_buf"]

    [[graphs.resources]]
    name = "parent_buf"
    ty = "Buffer"
    n = 2
