[workspace]
members = [
    "flow-rs",
    "flow-derive",
    "flow-plugins",
    "flow-debugger",
    "flow-message",
    "flow-quickstart",
]

[profile.dev]
incremental = false
panic = 'abort'

[profile.release]
panic = 'abort'
