main = "image"

[[nodes]]
name = "det"
ty = "Detect"
device = "cpu"
device_id = 0

[[nodes]]
name = "attr"
ty = "Attribute"
device = "cpu"
device_id = 0

[[graphs]]
name = "subgraph"
inputs = [{ name = "inp", cap = 16, ports = ["det:inp"] }]
outputs = [{ name = "out", cap = 16, ports = ["attr:out"] }]
connections = [
  { cap = 16, ports = ["det:out", "attr:inp"] },
]

[[graphs]]
name = "image"
connections = [
  { cap = 16, ports = ["source:out", "destination:inp"] },
  { cap = 16, ports = ["source:inp", "destination:out"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "VideoServer"
    port = 8080
    
    [[graphs.nodes]]
    name = "destination"
    ty = "subgraph"
