main = "video"

[[graphs]]
name = "video"
connections = [
    { cap=16, ports=["server:inp", "trans:out"] },
    { cap=16, ports=["server:out", "trans:inp"] }
]

    [[graphs.nodes]]
    name = "server"
    ty = "VideoServer"
    port = 8080

    [[graphs.nodes]]
    name = "trans"
    ty = "Transform"
