main = "Example"
[[graphs]]
name = "Example"

{{ Args = { 'Node': 10, 'Data': 1 } -}}

[[graphs.connections]]
cap = 64
ports = ["src:out", "trans0:inp"]
[[graphs.connections]]
cap = 64
ports = ["sink:inp", "trans{{Args.Node-1}}:out"]

{% for i in range(Args.Node-1) %}
[[graphs.connections]]
cap = 64
ports = ["trans{{i+1}}:inp", "trans{{i}}:out"]
{% end for %}

    {% for i in range(Args.Node) %}
    [[graphs.nodes]]
    name = "trans{{i}}"
    ty = "Transport"
    {% end for %}
    
    [[graphs.nodes]]
    name = "src"
    ty = "Source"
    n = {{Args.Data}}
    
    [[graphs.nodes]]
    name = "sink"
    ty = "Sink"
    data_n = {{Args.Data}}
    node_n = {{Args.Node}}
