main = "cat_finder_image"

[[graphs]]
name = "subgraph"
inputs = [{ name = "inp", cap = 16, ports = ["det:inp"] }]
outputs = [{ name = "out", cap = 16, ports = ["redis_proxy:out"] }]
connections = [
  { cap = 16, ports = ["det:out", "reid_image:inp"] },
  { cap = 16, ports = ["reid_image:out", "redis_proxy:inp"] },
]

    [[graphs.nodes]]
    name = "det"
    ty = "Detect"
    model = "yolox-s"
    conf = 0.25
    nms = 0.45
    tsize = 640
    path = "models/cat_finder_models/yolox_s.mge"
    interval = 1
    visualize = 1
    device = "cpu"
    device_id = 0
    
    [[graphs.nodes]]
    name = "reid_image"
    ty = "ReIDImage"
    path = "models/cat_finder_models/resnet50.mge"
    device = "cpu"
    device_id = 1

    [[graphs.nodes]]
    name = "redis_proxy"
    ty = "RedisProxy"
    ip = "127.0.0.1"
    port = "6379"
    mode = "save"
    prefix = "feature."

[[graphs]]
name = "cat_finder_image"
connections = [
  { cap = 16, ports = ["source:out", "destination:inp"] },
  { cap = 16, ports = ["source:inp", "destination:out"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "ImageServer"
    port = 8081
    
    [[graphs.nodes]]
    name = "destination"
    ty = "subgraph"
