main = "batch"

[[graphs]]
name = "batch"

connections = [
    {cap=4, ports=["gen:out", "group:inp"]},
    {cap=4, ports=["printer:inp", "group:out"]}
]

[[graphs.nodes]]
name = "printer"
ty = "Printer"

[[graphs.nodes]]
name = "gen"
ty = "Gen"
n = 23

[[graphs.nodes]]
name = "group"
ty = "Group"
id = 0
batch_size = 5
timeout = 2000
