[package]
name = "flow-derive"
version = "0.3.5"
authors = ["megvii"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"
proc-macro2 = {version ="1", features= ["span-locations"]}
anyhow = "1.0.38"

[dev-dependencies]
flow-rs = { path = "../flow-rs" }
toml = "0.5.8"
