[package]
name = "flow-message"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
dashmap = "4.0.2"
enum-as-inner = "0.3.3"
im = "15.0.0"
paste = "1.0.5"
pyo3 = "0.14.4"
