name: codecov
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt update && sudo apt install yasm
      - run: cargo build
      - run: sudo apt install python3.8-dev
      - run: cargo test
      - uses: maboesanman/rust-codecov@v0