name: macos-x86-cpu
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    name: macos-x86-cpu
    runs-on: macos-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: brew install yasm
      - run: brew install openssl@1.1
      - run: brew install pkg-config
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: cd $HOME && git clone https://github.com/tpoisonooo/rust-ffmpeg && cd rust-ffmpeg && git checkout dylib && cargo build
      - run: cat ${HOME}/megflow_ffmpeg_dynamic_link.sh
      - run: ls -alh `cat ${HOME}/megflow_ffmpeg_dynamic_link.sh | head -n 1`/lib/
      - run: echo 'export FFMPEG_DIR=`cat ${HOME}/megflow_ffmpeg_dynamic_link.sh | head -n 1`' >> $HOME/myenv
      - run: echo 'export CARGO_FEATURE_PREBUILD="PREBUILD"' >> $HOME/myenv
      - run: echo 'export LD_LIBRARY_PATH=${FFMPEG_DIR}/lib:${LD_LIBRARY_PATH}' >> $HOME/myenv
      - run: echo 'export PKG_CONFIG_PATH=${FFMPEG_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}' >> $HOME/myenv
      - run: chmod +x $HOME/myenv
      - run: cat $HOME/myenv
      - run: . $HOME/myenv && cargo test
      - run: . $HOME/myenv && cd flow-python && python3.8 setup.py install --user
      - run: . $HOME/myenv && cd flow-python/examples && cargo run --release --features="flow-plugins/python" --example megflow_run -- -p logical_test
