name: macos-x86-cpu
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    name: macos-x86-cpu
    runs-on: macos-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: brew install yasm
      - run: brew install openssl@1.1
      - run: brew install pkg-config
      - run: cargo build
      - run: cargo test
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: cd flow-python && python3.8 setup.py install --user
      - run: cd flow-python/examples && cargo run --example megflow_run -- -p logical_test
