name: pylint-doc-check
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    name: ubuntu-x86-cpu
    runs-on: ubuntu-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python ci/doc_link_checker.py
      - run: ./ci/run_pylint_check.sh
