name: ubuntu-x86-cpu
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    name: ubuntu-x86-cpu
    runs-on: ubuntu-latest
    steps:
      - name: cancel-previous-runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt update && sudo apt install yasm
      - run: sudo apt install -y libssl-dev
      - run: sudo apt update && sudo apt-get install -y pkg-config --fix-missing
      - run: sudo apt install -y libv4l-dev liblzma-dev
      - run: cd $HOME && git clone https://github.com/tpoisonooo/rust-ffmpeg && cd rust-ffmpeg && git checkout dylib && cargo build
      - run: echo 'export FFMPEG_DIR=`cat ${HOME}/megflow_ffmpeg_dynamic_link.sh | head -n 1`' >> $HOME/myenv
      - run: echo 'export CARGO_FEATURE_PREBUILD="PREBUILD"' >> $HOME/myenv
      - run: echo 'export LD_LIBRARY_PATH=${FFMPEG_DIR}/lib:${LD_LIBRARY_PATH}' >> $HOME/myenv
      - run: echo 'export PKG_CONFIG_PATH=${FFMPEG_DIR}/lib/pkgconfig:${PKG_CONFIG_PATH}' >> $HOME/myenv
      - run: chmod +x $HOME/myenv
      - run: sudo apt install python3.8-dev
      - run: . $HOME/myenv && cargo test --release
      - run: . $HOME/myenv && cd flow-python && python3 setup.py install --user && cd examples && megflow_run -p logical_test

